language: node_js
node_js:
- node
- '8'
- '7'
- '6'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test-for-travis
after_success:
- env
- test "${TRAVIS_NODE_VERSION}" == "8" && test "${TRAVIS_TEST_RESULT}" == "0" && npm run build
- ls -la dist/
jobs:
  include:
  - stage: npm release
    node_js: 8
    script:
    - if [ -n "$TRAVIS_TAG" ]; then echo "Deploying version ${TRAVIS_TAG} to npm...";
      fi
    deploy:
      provider: npm
      email: info@labs64.com
      api_key:
        secure: Z2U2N0FMjpkqFK+YGaGPAADFuuExTB1UJ58FMwD/tz/EnNLXlUxiPHVEIVWvU6PeDXkT6cYZMsvWZDOiGNMcZo00714HWVBX9t7n6Ztd2CVMZ1vkqyXYZiYVhs+p4qe6nH6QYsKe9vCjJd1lSYJQH0dn+PGYtfGF4CZAGc6TBBBDrqEgT4Z7Y1MIE4jqDHRNybUEzH1pMp6E80z8izaHG26qYJ4+gALgfK3GVj+FwpGMF/T9W3XYA4PNEw+c/QaucrZBN15XHIp1QlODgU7aMehnXoNgC2zLwjXHGzKtsidxgjSYPP9MfZ0oSxqsEaMxLXM+L3Oh2jcM1OTs3pn46jtu46vUblyHBgFCLnpQgYJVJrjfJkux+dM7Ux2TF+F3aUFf7st2hUMHa2uOuz4syJn9ZkhKT3ZIWKUC7aYuuhxPVmXhCbb+o9+y+A1lqrduG5/vY21rBM+80IWO098lAkFF1EEn5Q0qzUh7ukUNLttDnuUgF3jcHU6fRAh/EsliqVtpjApkTHP4SA07R/K4v6cHJuZjjWbVOmOvtLlrfSiwvCKbTFGYIdiojMzNvVuvnEE67p0A8Rpa5F/PK0zzMPIYrKMA4VwRPvlCnaDprPUfSpyrVxa5kjbtZ3hRJpDoTuFKRqCSscx9uub/Q2vzQ4t70ll1rTZX/t0B6EmGiJ0=
      on:
        tags: true
