language: node_js

node_js:
  - "node"
  - "8"
  - "7"
  - "6"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp travis-test
  - gulp release
  - ls -la dist/
