language: node_js

node_js:
  - stable

env:
  - NODEJS_VERSION=6.10.3

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - nvm install $NODEJS_VERSION
  - npm install
  
script:
  - gulp travis-test
  - gulp release
  - ls -la
