language: node_js

node_js:
  - "node"
  - "7"
  - "6"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp travis-test

after_success:
  - env
  - test "${TRAVIS_NODE_VERSION}" == "node" && test "${TRAVIS_TEST_RESULT}" == "0" && gulp dist
  - ls -la dist/
