/**
 * @author    Labs64 <netlicensing@labs64.com>
 * @license   Apache-2.0
 * @link      http://netlicensing.io
 * @copyright 2017 Labs64 NetLicensing
 */

/**
 * Transaction entity used internally by NetLicensing.
 *
 * Properties visible via NetLicensing API:
 *
 * Unique number (across all products of a vendor) that identifies the transaction. This number is
 * always generated by NetLicensing.
 * @property string number
 *
 * always true for transactions
 * @property boolean active
 *
 * Status of transaction. "CANCELLED", "CLOSED", "PENDING".
 * @property string status
 *
 * "SHOP". AUTO transaction for internal use only.
 * @property string source
 *
 * grand total for SHOP transaction (see source).
 * @property float grandTotal
 *
 * discount for SHOP transaction (see source).
 * @property float discount
 *
 * specifies currency for money fields (grandTotal and discount). Check data types to discover which
 * @property string currency
 *
 * Date created. Optional.
 * @property string dateCreated
 *
 * Date closed. Optional.
 * @property string dateClosed
 *
 * @constructor
 */

function Transaction() {
    BaseEntity.apply(this, arguments);

    //The attributes that should be cast to native types.
    Object.defineProperty(this, 'casts', {
        value: {
            active: 'boolean',
            grandTotal: 'float',
            discount: 'float'
        }
    });

    //define default entity properties
    this.__defines(['number', 'name', 'status', 'source', 'grandTotal', 'discount', 'currency', 'dateCreated', 'dateClosed']);
    this.__define('active', true);
}

Transaction.prototype = Object.create(BaseEntity.prototype);
Transaction.prototype.constructor = Transaction;

Transaction.prototype.setNumber = function (number) {
    return this.setProperty('number', number);
};

Transaction.prototype.getNumber = function (def) {
    return this.getProperty('number', def);
};

Transaction.prototype.setName = function (name) {
    return this.setProperty('name', name);
};

Transaction.prototype.getName = function (def) {
    return this.getProperty('name', def);
};

Transaction.prototype.setStatus = function (status) {
    return this.setProperty('status', status);
};

Transaction.prototype.getStatus = function (def) {
    return this.getProperty('status', def);
};

Transaction.prototype.setSource = function (source) {
    return this.setProperty('source', source);
};

Transaction.prototype.getSource = function (def) {
    return this.getProperty('source', def);
};

Transaction.prototype.setGrandTotal = function (grandTotal) {
    return this.setProperty('grandTotal', grandTotal);
};

Transaction.prototype.getGrandTotal = function (def) {
    return this.getProperty('grandTotal', def);
};

Transaction.prototype.setDiscount = function (discount) {
    return this.setProperty('discount', discount);
};

Transaction.prototype.getDiscount = function (def) {
    return this.getProperty('discount', def);
};

Transaction.prototype.setCurrency = function (currency) {
    return this.setProperty('currency', currency);
};

Transaction.prototype.getCurrency = function (def) {
    return this.getProperty('currency', def);
};

Transaction.prototype.setDateCreated = function (dateCreated) {
    return this.setProperty('dateCreated', dateCreated);
};

Transaction.prototype.getDateCreated = function (def) {
    return this.getProperty('dateCreated', def);
};

Transaction.prototype.setDateClosed = function (dateClosed) {
    return this.setProperty('dateClosed', dateClosed);
};

Transaction.prototype.getDateClosed = function (def) {
    return this.getProperty('dateClosed', def);
};

Transaction.prototype.setActive = function () {
    return this.setProperty('active', true);
};
